In [1]:
from numpy import array
import math

In [2]:
def obja(x,mode):
    global numf, numg, numH
    z = ()
    if mode == 1:
        numf += 1
        z += (x[0]**2 + 5*(x[1]**2) + x[0] - 5*x[1],)
    if mode == 2:
        numg += 1
        z = z + (array([2*x[0] + 1, 10*x[1] - 5]),)
    if mode == 3:
        numH += 1
        z = z + (array([[2, 0], [0, 10]]),)
    return z

In [3]:
numf = 0; numg = 0; numH = 0

f = obja(array([1, 2]),3)

print(f, numf, numg, numH)

(array([[ 2,  0],
       [ 0, 10]]),) 0 0 1


In [4]:
f = obja(array([1, 2]),1)

print(f, numf, numg, numH)

(12,) 1 0 1


In [5]:
def obja(x,mode):
    global numf, numg, numH
    z = ()
    if mode == 1:
        numf += 1
        z += (math.cos(x[0]) + math.exp(-x[0]),)
    if mode == 2:
        numg += 1
        z = z + (array([-math.sin(x[0]) - math.exp(-x[0])]),)
    if mode == 3:
        numH += 1
        z = z + (array([-math.cos(x[0]) + math.exp(-x[0])]),)
    return z

In [6]:
numf = 0; numg = 0; numH = 0

f = obja(array([2]),3)

print(f, numf, numg, numH)

(array([0.55148212]),) 0 0 1


In [7]:
f1 = obja(array([math.pi/2]),1)
print(f1, numf, numg, numH)
f2 = obja(array([math.pi/2]),2)
print(f2, numf, numg, numH)
f3 = obja(array([math.pi/2]),3)
print(f3, numf, numg, numH)

(0.20787957635076199,) 1 0 1
(array([-1.20787958]),) 1 1 1
(array([0.20787958]),) 1 1 2


In [8]:
f2[0][0]*f3[0][0]

-0.2510934946145341

In [9]:
f = obja(array([3*math.pi/2]),1)
print(f, numf, numg, numH)
f = obja(array([3*math.pi/2]),2)
print(f, numf, numg, numH)
f = obja(array([3*math.pi/2]),3)
print(f, numf, numg, numH)

(0.008983291021129245,) 2 1 2
(array([0.99101671]),) 2 2 2
(array([0.00898329]),) 2 2 3


In [10]:
from bisectS import bisect

In [11]:
numf = 0; numg = 0; numH = 0
result = bisect(obja, math.pi/2, 3*math.pi/2, 1E-4)

In [12]:
print('Interval of stationary point is [%f, %f]' % (result[0], result[1]))
print('Number of iterations %f' % (result[2]))
print('Number of function evaluations used %f' % (numf + numg + numH))

Interval of stationary point is [3.183010, 3.183106]
Number of iterations 15.000000
Number of function evaluations used 32.000000
